version: '3.8'

services:
  file-preview:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./cache:/app/cache
      - ./download:/app/download
      - ./log:/app/log
      - ./convert:/app/convert
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - MAX_CONTENT_LENGTH=104857600
    restart: unless-stopped

  file-preview-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./cache:/app/cache
      - ./download:/app/download
      - ./log:/app/log
      - ./convert:/app/convert
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - MAX_CONTENT_LENGTH=104857600
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 