# 文件预览服务配置

# 目录配置
directories:
  # 缓存目录
  cache: "/tmp/file_preview/cache"
  # 下载目录
  download: "/tmp/file_preview/download"
  # 转换目录
  convert: "/tmp/file_preview/convert"
  # 日志目录
  log: "/tmp/file_preview/log"

# 服务器配置
server:
  # 主机
  host: "127.0.0.1"
  # 端口
  port: 5001
  # 最大上传大小（字节）
  max_content_length: 104857600  # 100MB = 100 * 1024 * 1024 字节

# 缓存配置
cache:
  retention_days: 7                    # 缓存保留天数
  max_size: 1024                       # 最大缓存大小（MB）

# Redis配置
redis:
  # 是否启用Redis缓存
  enabled: false
  # Redis主机
  host: "localhost"
  # Redis端口
  port: 6379
  # Redis数据库索引
  db: 0
  # Redis密码
  password: null
  # Redis键前缀
  prefix: "file_preview:"

# 日志配置
logging:
  level: INFO                          # 日志级别
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# 性能配置
performance:
  max_workers: 4                       # 最大工作线程数
  download_timeout: 30                 # 下载超时时间（秒）
  keep_original_name: true             # 是否保留原始文件名
  enable_multithreading: true          # 是否启用多线程模式
  worker_processes: 2                  # 工作进程数

# 转换配置
conversion:
  # LibreOffice 路径
  libreoffice_path: "/opt/homebrew/bin/soffice"
  # 转换超时时间（秒）
  timeout: 300
  # 重试次数
  retry_times: 3
  # 支持的文件格式
  supported_formats:
    - ".doc"
    - ".docx"
    - ".xls"
    - ".xlsx"
    - ".ppt"
    - ".pptx"
    - ".odt"
    - ".ods"
    - ".odp"