name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Check config file
        run: |
          if [ ! -f "config/config.yaml" ]; then
            echo "Error: config/config.yaml not found"
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/file-preview:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/file-preview:${{ github.ref_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Check config file
        run: |
          if [ ! -f "config/config.yaml" ]; then
            echo "Error: config/config.yaml not found"
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build binaries
        run: |
          pyinstaller --clean --onefile \
            --add-data "config/config.yaml:config" \
            --add-data "file_preview:file_preview" \
            file_preview/cli/main.py

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 